from dotenv import load_dotenv
import os
load_dotenv()
ACCESS_SECRETKEY=os.getenv("ACCESS_SECRETKEY")
ALGORITHM=os.getenv("ALGORITHM")
ACCESS_TOKEN_EXPIRE_TIME=os.getenv("ACCESSTOKENEXPIRETIME")
DATABASEURL=os.getenv("DATABASEURL")
REFRESH_TOKEN_EXPIRE_TIME=os.getenv("REFRESHTOKENEXPIRETIME")
REFRESH_SECRETKEY=os.getenv("REFRESH_SECRETKEY")