"""inventory

Revision ID: 0442d8625675
Revises: daeec255be2e
Create Date: 2026-08-25 23:21:46.853017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0442d8625675'
down_revision: Union[str, Sequence[str], None] = 'daeec255be2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('form', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('dosage_num', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('dosage_unit', sa.String(length=20), nullable=False),
    sa.Column('minimum_stock', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine')
    # ### end Alembic commands ###
