import { Medicine, Customer, Supplier, Employee, Order, AIPredictiveAlert, UserProfile } from './types';

export const initialUserProfile: UserProfile = {
  name: 'Dr. Sarah Jenkins',
  role: 'Clinical Lead & Inventory Director',
  title: 'Lead Clinician',
  department: 'Pharmacy Operations',
  email: 'clinician@livsera.com',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6AQz9SGXkI2ldShhEkdIkv2Qej-ifRNpgFY5TcHrD99ND3UzhdkpnRwTEJV2UvXPAqB4Ap2l8IirDl3Bzeat8b7lwxQ-QI7jBeRWeRq3AjC39bn4jhwlCxq4qSIj4HbDFnhO_jiJGGlcs-Gtq0rXtczW7SiUzYq8W0ShkPF5vbp3zFT7D5d1ln_mmcCcQnkAG_yJa8QVCJz16rUJmX4VdgUX9Z0DOxm0l_t38A1f58949l9yszQAvvw',
};

export const initialMedicines: Medicine[] = [
  {
    id: 'med-amx-500',
    sku: 'MED-AMX-500-001',
    name: 'Amoxicillin 500mg',
    category: 'Antibiotic',
    dosage: '500mg Capsules',
    form: 'Box of 100',
    manufacturer: 'PharmaCorp Inc.',
    supplier: 'PharmaCorp Inc.',
    unitPrice: 12.50,
    currentStock: 1240,
    threshold: 500,
    minStock: 500,
    maxStock: 5000,
    storageLocation: 'Aisle 4, Shelf B2',
    earliestExpiry: '2024-11-15',
    status: 'In Stock',
    leadTimeDays: 5,
    predictedVelocity: 185,
    predictedStockoutDays: 7,
    riskLevel: 'High',
    aiConfidence: 92,
    avgDailyUsage: 42.5,
    description: 'Broad-spectrum penicillin antibiotic used to treat a wide variety of bacterial infections.',
    activeIngredient: 'Amoxicillin Trihydrate',
    usageTrend30Days: [30, 52, 37, 75, 120, 60, 135],
    movements: [
      {
        id: 'mov-1',
        date: 'Oct 12, 14:30',
        type: 'OUT',
        qty: -50,
        employee: 'Dr. Sarah Jenkins',
        notes: 'Ward B Resupply',
        batchNumber: 'BCH-2024-88A',
      },
      {
        id: 'mov-2',
        date: 'Oct 10, 09:15',
        type: 'IN',
        qty: 1000,
        employee: 'Mike Ross (Admin)',
        notes: 'PO-2024-890 Received',
        batchNumber: 'BCH-2024-77X',
      },
      {
        id: 'mov-3',
        date: 'Oct 05, 11:20',
        type: 'OUT',
        qty: -120,
        employee: 'Nurse Ratched',
        notes: 'ER Emergency Stock',
        batchNumber: 'BCH-2024-65Z',
      },
      {
        id: 'mov-4',
        date: 'Sep 28, 16:45',
        type: 'OUT',
        qty: -80,
        employee: 'Dr. Elena Rostova',
        notes: 'Outpatient Dispensary',
        batchNumber: 'BCH-2024-65Z',
      },
      {
        id: 'mov-5',
        date: 'Sep 20, 10:00',
        type: 'IN',
        qty: 500,
        employee: 'Mike Ross (Admin)',
        notes: 'Monthly Routine Reorder',
        batchNumber: 'BCH-2024-52M',
      }
    ]
  },
  {
    id: 'med-lis-010',
    sku: 'LIS-010-TB',
    name: 'Lisinopril 10mg',
    category: 'Cardiovascular',
    dosage: '10mg Tablets',
    form: 'Bottle of 30',
    manufacturer: 'CardioCare Pharma',
    supplier: 'MediSupply Global',
    unitPrice: 8.00,
    currentStock: 850,
    threshold: 1000,
    minStock: 1000,
    maxStock: 4000,
    storageLocation: 'Aisle 2, Shelf C1',
    earliestExpiry: '2025-06-20',
    status: 'Low Stock',
    leadTimeDays: 4,
    predictedVelocity: 65,
    predictedStockoutDays: 13,
    riskLevel: 'Medium',
    aiConfidence: 78,
    avgDailyUsage: 35.0,
    description: 'ACE inhibitor prescribed for hypertension and congestive heart failure management.',
    activeIngredient: 'Lisinopril Dihydrate',
    usageTrend30Days: [25, 30, 42, 38, 45, 50, 48],
    movements: [
      {
        id: 'mov-lis-1',
        date: 'Oct 14, 08:30',
        type: 'OUT',
        qty: -60,
        employee: 'Dr. Sarah Jenkins',
        notes: 'Cardiology Clinic Dispensary',
        batchNumber: 'BCH-LIS-901',
      },
      {
        id: 'mov-lis-2',
        date: 'Oct 08, 14:10',
        type: 'OUT',
        qty: -90,
        employee: 'Dr. Elena Rostova',
        notes: 'Prescription refills batch 4',
        batchNumber: 'BCH-LIS-901',
      }
    ]
  },
  {
    id: 'med-epi-003',
    sku: 'EPI-PEN-03',
    name: 'Epinephrine Auto-Injector',
    category: 'Emergency',
    dosage: '0.3mg / 0.3ml',
    form: '2-Pack Auto-Injectors',
    manufacturer: 'BioEmergency Labs',
    supplier: 'LifeGuard Med',
    unitPrice: 145.00,
    currentStock: 12,
    threshold: 50,
    minStock: 50,
    maxStock: 300,
    storageLocation: 'Emergency Crash Cart Room A',
    earliestExpiry: '2025-02-28',
    status: 'Critical',
    leadTimeDays: 2,
    predictedVelocity: 6,
    predictedStockoutDays: 2,
    riskLevel: 'Critical',
    aiConfidence: 96,
    avgDailyUsage: 4.8,
    description: 'Emergency epinephrine injection for acute anaphylaxis and severe allergic emergencies.',
    activeIngredient: 'Epinephrine',
    usageTrend30Days: [4, 6, 3, 8, 5, 7, 9],
    movements: [
      {
        id: 'mov-epi-1',
        date: 'Oct 15, 02:15',
        type: 'OUT',
        qty: -4,
        employee: 'Nurse Ratched',
        notes: 'ER Trauma Code Blue Resupply',
        batchNumber: 'BCH-EPI-774',
      }
    ]
  },
  {
    id: 'med-ibu-400',
    sku: 'IBU-400-TB',
    name: 'Ibuprofen 400mg Tabs',
    category: 'Analgesics',
    dosage: '400mg Film-coated Tablets',
    form: 'Bottle of 500',
    manufacturer: 'Generic Health Co.',
    supplier: 'Generic Health Co.',
    unitPrice: 8.20,
    currentStock: 450,
    threshold: 5000,
    minStock: 1000,
    maxStock: 25000,
    storageLocation: 'Aisle 1, Shelf D4',
    earliestExpiry: '2026-03-15',
    status: 'Low Stock',
    leadTimeDays: 7,
    predictedVelocity: 210,
    predictedStockoutDays: 2,
    riskLevel: 'Critical',
    aiConfidence: 85,
    avgDailyUsage: 195.0,
    description: 'Nonsteroidal anti-inflammatory drug (NSAID) used for pain relief, fever reduction, and anti-inflammatory therapy.',
    activeIngredient: 'Ibuprofen',
    usageTrend30Days: [180, 210, 195, 240, 260, 205, 230],
    movements: [
      {
        id: 'mov-ibu-1',
        date: 'Oct 13, 11:00',
        type: 'OUT',
        qty: -200,
        employee: 'Mike Ross (Admin)',
        notes: 'Outpatient Pharmacy bulk request',
        batchNumber: 'BCH-IBU-332',
      }
    ]
  },
  {
    id: 'med-ppe-n95',
    sku: 'PPE-N95-BX',
    name: 'Surgical Masks (N95)',
    category: 'PPE',
    dosage: 'NIOSH Certified',
    form: 'Box of 50',
    manufacturer: 'SafeShield Technologies',
    supplier: 'SafeShield Supplies',
    unitPrice: 45.00,
    currentStock: 0,
    threshold: 2000,
    minStock: 2000,
    maxStock: 10000,
    storageLocation: 'Central Supply Warehouse B',
    earliestExpiry: '2027-10-01',
    status: 'Out of Stock',
    leadTimeDays: 3,
    predictedVelocity: 150,
    predictedStockoutDays: 0,
    riskLevel: 'Critical',
    aiConfidence: 99,
    avgDailyUsage: 140.0,
    description: 'Fluid resistant surgical respirator masks for infection control in clinical procedures.',
    activeIngredient: 'Melt-blown Polypropylene Filter',
    usageTrend30Days: [120, 150, 140, 180, 210, 190, 250],
    movements: [
      {
        id: 'mov-ppe-1',
        date: 'Oct 11, 17:00',
        type: 'OUT',
        qty: -150,
        employee: 'Nurse Ratched',
        notes: 'Depleted remaining ICU stock',
        batchNumber: 'BCH-PPE-909',
      }
    ]
  },
  {
    id: 'med-para-500',
    sku: 'PARA-500-BTL',
    name: 'Paracetamol 500mg',
    category: 'Analgesics',
    dosage: '500mg Tablets',
    form: 'Bottle of 1000',
    manufacturer: 'Apex Pharma',
    supplier: 'MediSupply Global',
    unitPrice: 6.50,
    currentStock: 850,
    threshold: 1000,
    minStock: 1000,
    maxStock: 8000,
    storageLocation: 'Aisle 1, Shelf B1',
    earliestExpiry: '2025-08-14',
    status: 'Low Stock',
    leadTimeDays: 3,
    predictedVelocity: 280,
    predictedStockoutDays: 3,
    riskLevel: 'Critical',
    aiConfidence: 98,
    avgDailyUsage: 250.0,
    description: 'Widely used analgesic and antipyretic for mild-to-moderate pain and fever reduction.',
    activeIngredient: 'Acetaminophen / Paracetamol',
    usageTrend30Days: [220, 240, 250, 290, 310, 280, 340],
    movements: [
      {
        id: 'mov-para-1',
        date: 'Oct 14, 09:20',
        type: 'OUT',
        qty: -300,
        employee: 'Dr. Elena Rostova',
        notes: 'Inpatient wards distribution',
        batchNumber: 'BCH-PAR-104',
      }
    ]
  },
  {
    id: 'med-ato-020',
    sku: 'ATO-20-TAB',
    name: 'Atorvastatin 20mg',
    category: 'Cardiovascular',
    dosage: '20mg Tablets',
    form: 'Bottle of 90',
    manufacturer: 'LipidCare Labs',
    supplier: 'PharmaCorp Inc.',
    unitPrice: 18.90,
    currentStock: 450,
    threshold: 600,
    minStock: 600,
    maxStock: 3000,
    storageLocation: 'Aisle 2, Shelf A3',
    earliestExpiry: '2025-12-30',
    status: 'Low Stock',
    leadTimeDays: 4,
    predictedVelocity: 110,
    predictedStockoutDays: 4,
    riskLevel: 'Critical',
    aiConfidence: 94,
    avgDailyUsage: 85.0,
    description: 'HMG-CoA reductase inhibitor (statin) used to lower cholesterol and prevent cardiovascular events.',
    activeIngredient: 'Atorvastatin Calcium',
    usageTrend30Days: [75, 80, 85, 95, 110, 90, 120],
    movements: [
      {
        id: 'mov-ato-1',
        date: 'Oct 13, 15:40',
        type: 'OUT',
        qty: -150,
        employee: 'Dr. Sarah Jenkins',
        notes: 'Outpatient Cardiac Clinic',
        batchNumber: 'BCH-ATO-440',
      }
    ]
  },
  {
    id: 'med-ome-020',
    sku: 'OME-20-CAP',
    name: 'Omeprazole 20mg',
    category: 'Gastroenterology',
    dosage: '20mg Delayed-Release Capsules',
    form: 'Bottle of 100',
    manufacturer: 'GastroHealth Labs',
    supplier: 'Generic Health Co.',
    unitPrice: 11.20,
    currentStock: 55,
    threshold: 100,
    minStock: 100,
    maxStock: 1500,
    storageLocation: 'Aisle 3, Shelf B1',
    earliestExpiry: '2025-09-18',
    status: 'Low Stock',
    leadTimeDays: 4,
    predictedVelocity: 25,
    predictedStockoutDays: 2,
    riskLevel: 'High',
    aiConfidence: 89,
    avgDailyUsage: 22.0,
    description: 'Proton pump inhibitor that decreases stomach acid production for GERD and ulcer therapy.',
    activeIngredient: 'Omeprazole',
    usageTrend30Days: [18, 22, 20, 26, 25, 24, 30],
    movements: [
      {
        id: 'mov-ome-1',
        date: 'Oct 12, 10:15',
        type: 'OUT',
        qty: -45,
        employee: 'Dr. Elena Rostova',
        notes: 'GI Clinic routine requisition',
        batchNumber: 'BCH-OME-118',
      }
    ]
  },
  {
    id: 'med-met-500',
    sku: 'MED-9923',
    name: 'Metformin 500mg',
    category: 'Endocrinology',
    dosage: '500mg Extended Release',
    form: 'Bottle of 100',
    manufacturer: 'DiabeticCare Global',
    supplier: 'MediSupply Global',
    unitPrice: 5.50,
    currentStock: 2100,
    threshold: 800,
    minStock: 800,
    maxStock: 6000,
    storageLocation: 'Aisle 3, Shelf D2',
    earliestExpiry: '2026-07-22',
    status: 'In Stock',
    leadTimeDays: 3,
    predictedVelocity: 70,
    predictedStockoutDays: 30,
    riskLevel: 'Low',
    aiConfidence: 88,
    avgDailyUsage: 65.0,
    description: 'First-line medication for the treatment of type 2 diabetes.',
    activeIngredient: 'Metformin Hydrochloride',
    usageTrend30Days: [60, 65, 62, 70, 68, 72, 69],
    movements: []
  },
  {
    id: 'med-sgp-1092',
    sku: 'SGP-1092',
    name: 'Surgical Gloves (L)',
    category: 'PPE',
    dosage: 'Sterile Powder-Free Latex',
    form: 'Box of 100 Pairs',
    manufacturer: 'MediShield Global',
    supplier: 'SafeShield Supplies',
    unitPrice: 45.00,
    currentStock: 0,
    threshold: 500,
    minStock: 500,
    maxStock: 4000,
    storageLocation: 'Operating Theater Supply Room 2',
    earliestExpiry: '2027-05-15',
    status: 'Critical',
    leadTimeDays: 3,
    predictedVelocity: 60,
    predictedStockoutDays: 0,
    riskLevel: 'Critical',
    aiConfidence: 97,
    avgDailyUsage: 55.0,
    description: 'High tensile strength sterile gloves for surgical and sterile interventional procedures.',
    activeIngredient: 'Natural Rubber Latex',
    usageTrend30Days: [45, 50, 52, 60, 58, 65, 70],
    movements: []
  }
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'City Central Pharmacy',
    contactPerson: 'Dr. Sarah Jenkins',
    email: 'sarah.jenkins@citycentralpharm.com',
    phone: '+1 (555) 234-5678',
    address: '123 Main St., Healthcare District, Suite 400',
    paymentTerms: 'Net 30 Terms',
    totalOrders: 48,
    totalSpend: 54200.00,
    status: 'Active',
  },
  {
    id: 'cust-2',
    name: 'Mercy Hospital',
    contactPerson: 'Director Marcus Vance',
    email: 'purchasing@mercygeneral.org',
    phone: '+1 (555) 890-1234',
    address: '742 Evergreen Blvd, Medical Campus Wing A',
    paymentTerms: 'Net 45 Terms',
    totalOrders: 112,
    totalSpend: 245000.00,
    status: 'Active',
  },
  {
    id: 'cust-3',
    name: 'City Clinic',
    contactPerson: 'Dr. Robert Lin',
    email: 'supplies@cityclinicgroup.com',
    phone: '+1 (555) 432-8765',
    address: '890 Harbor Way, South Pavilion',
    paymentTerms: 'Net 30 Terms',
    totalOrders: 34,
    totalSpend: 31200.00,
    status: 'Active',
  },
  {
    id: 'cust-4',
    name: 'Dr. Smith Practice',
    contactPerson: 'Dr. Gregory Smith',
    email: 'admin@drsmithfamilypractice.com',
    phone: '+1 (555) 678-9012',
    address: '45 Doctors Park, Suite 102',
    paymentTerms: 'Net 15 Terms',
    totalOrders: 22,
    totalSpend: 18450.00,
    status: 'Active',
  },
  {
    id: 'cust-5',
    name: 'Central Pharmacy',
    contactPerson: 'Pharm. Angela Ray',
    email: 'orders@centralrxchain.com',
    phone: '+1 (555) 321-7654',
    address: '500 Commerce Ave, Unit 12',
    paymentTerms: 'Net 30 Terms',
    totalOrders: 65,
    totalSpend: 89700.00,
    status: 'Active',
  }
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'PharmaCorp Inc.',
    contactPerson: 'James Thornton',
    email: 'orders@pharmacorp.com',
    phone: '+1 (800) 555-0199',
    category: 'Pharmaceuticals & Antibiotics',
    leadTimeDays: 5,
    rating: 4.9,
    activeOrdersCount: 3,
    address: '100 Innovation Parkway, Boston, MA',
  },
  {
    id: 'sup-2',
    name: 'MediSupply Global',
    contactPerson: 'Elena Vasquez',
    email: 'enterprise@medisupplyglobal.com',
    phone: '+1 (800) 555-0244',
    category: 'Cardiovascular & General Rx',
    leadTimeDays: 4,
    rating: 4.8,
    activeOrdersCount: 2,
    address: '450 Distribution Way, Chicago, IL',
  },
  {
    id: 'sup-3',
    name: 'LifeGuard Med',
    contactPerson: 'Arthur Pendelton',
    email: 'emergency@lifeguardmed.com',
    phone: '+1 (800) 555-0377',
    category: 'Emergency & Critical Care',
    leadTimeDays: 2,
    rating: 4.95,
    activeOrdersCount: 1,
    address: '77 Life sciences Way, San Diego, CA',
  },
  {
    id: 'sup-4',
    name: 'Generic Health Co.',
    contactPerson: 'Melissa Wong',
    email: 'logistics@generichealth.com',
    phone: '+1 (800) 555-0488',
    category: 'Analgesics & OTC Formulations',
    leadTimeDays: 7,
    rating: 4.6,
    activeOrdersCount: 4,
    address: '900 Bulk Logistics Blvd, Dallas, TX',
  },
  {
    id: 'sup-5',
    name: 'SafeShield Supplies',
    contactPerson: 'Kevin Miller',
    email: 'contracts@safeshieldppe.com',
    phone: '+1 (800) 555-0566',
    category: 'PPE & Infection Control',
    leadTimeDays: 3,
    rating: 4.7,
    activeOrdersCount: 2,
    address: '320 Cleanroom Dr, Minneapolis, MN',
  }
];

export const initialEmployees: Employee[] = [
  {
    id: 'emp-1',
    name: 'Dr. Sarah Jenkins',
    role: 'Clinical Director & Lead Pharmacist',
    department: 'Clinical Pharmacy',
    email: 'sarah.jenkins@livsera.com',
    phone: '+1 (555) 201-8841',
    shift: 'Day Shift (07:00 - 15:30)',
    status: 'Active',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD6AQz9SGXkI2ldShhEkdIkv2Qej-ifRNpgFY5TcHrD99ND3UzhdkpnRwTEJV2UvXPAqB4Ap2l8IirDl3Bzeat8b7lwxQ-QI7jBeRWeRq3AjC39bn4jhwlCxq4qSIj4HbDFnhO_jiJGGlcs-Gtq0rXtczW7SiUzYq8W0ShkPF5vbp3zFT7D5d1ln_mmcCcQnkAG_yJa8QVCJz16rUJmX4VdgUX9Z0DOxm0l_t38A1f58949l9yszQAvvw',
  },
  {
    id: 'emp-2',
    name: 'Mike Ross',
    role: 'Inventory Systems Administrator',
    department: 'Supply Chain Operations',
    email: 'mike.ross@livsera.com',
    phone: '+1 (555) 201-8842',
    shift: 'Day Shift (08:00 - 16:30)',
    status: 'Active',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUx7gLhxlHcwRMjKc0tKz4MZSTU7XAx3gKGjGR_zn2Yqj8G62OO_D6XjFHkW_i6a87sfInTT_PjUVEgjl2VOERkR0ZKTvGPz8ppkKsxbHqfFc8lqPLy56vEUmzxeOLa_Hq8Glqc33Lm9enjwdjDOvJIxs4QBh1LapIUuRwfyFNMT3A54nNJcEjezA19rS5dm2udUJAYLldHGXaKk11ZzCGN-mkchqR_yGPw4jK9Ab2HIARBEuBMO3pMg',
  },
  {
    id: 'emp-3',
    name: 'Nurse Ratched',
    role: 'ER Charge Nurse & Crash Cart Manager',
    department: 'Emergency Medicine',
    email: 'ratched.er@livsera.com',
    phone: '+1 (555) 201-8843',
    shift: 'Night Shift (19:00 - 07:30)',
    status: 'Active',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDz8uRJTavdYdJr7-opL0O09r3wawZwDx1hjk4WRMmJ6AT5O1RFMOF7KeGzrR_lxACVEton0PoGnGGNFa6m_O_kvLcGXU1_8nwCKKDselntuQmC_a6Kz3SsfNwDE-OewuH8cNHAeqUVsCbPdyFy7H3qBJSukJXmVGltnUf0yIbjJKHMBa6DZSD_HtInHe_1FUJrTxk71eob4AtY-JhE8drki3_HXPh5YhOxynaJuDHRMm-cyePcjo7vsg',
  },
  {
    id: 'emp-4',
    name: 'Dr. Elena Rostova',
    role: 'Formulary & Therapeutics Specialist',
    department: 'Pharmacy Services',
    email: 'elena.rostova@livsera.com',
    phone: '+1 (555) 201-8844',
    shift: 'Day Shift (08:30 - 17:00)',
    status: 'Active',
    avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAFHbUjuT6-8zm_-PHL5XoAXU8Nc5HcBPfcDY__D4Q18wnNe3uD7Gog5b6gaKxfEqx4e-Z971Y6L9QbekwWxrEzK9IYhQrlY2m8WDQhMIBYc8L8LFv_GTXAxGbQMHLL5xmgN_loqy5A_cqzLeYMLiM__37q2SLgzu9e5EBnQq9xcRv-W2ZpMRzwDqEd94tjwREGaG4KIi2UwCq4MBtNzAibn14L8TG-uJtQI2-LBqjzsmbUEXs_C9qXEw',
  }
];

export const initialOrders: Order[] = [
  {
    id: '#ORD-0921',
    customer: 'Mercy Hospital',
    customerId: 'cust-2',
    customerContact: 'Director Marcus Vance',
    items: [
      {
        id: 'item-1',
        medicineId: 'med-amx-500',
        medicineName: 'Amoxicillin 500mg',
        sku: 'MED-AMX-500-001',
        quantity: 80,
        unitPrice: 12.50,
        total: 1000.00,
      },
      {
        id: 'item-2',
        medicineId: 'med-lis-010',
        medicineName: 'Lisinopril 10mg',
        sku: 'LIS-010-TB',
        quantity: 31,
        unitPrice: 8.00,
        total: 248.00,
      }
    ],
    subtotal: 1248.00,
    discount: 0,
    tax: 2.00,
    total: 1250.00,
    status: 'Success',
    date: 'Today, 10:42 AM',
    notes: 'Urgent delivery to ICU Pharmacy Wing B',
    paymentTerms: 'Net 45 Terms',
  },
  {
    id: '#ORD-0920',
    customer: 'City Clinic',
    customerId: 'cust-3',
    customerContact: 'Dr. Robert Lin',
    items: [
      {
        id: 'item-3',
        medicineId: 'med-ibu-400',
        medicineName: 'Ibuprofen 400mg Tabs',
        sku: 'IBU-400-TB',
        quantity: 50,
        unitPrice: 8.20,
        total: 410.00,
      }
    ],
    subtotal: 410.00,
    discount: 0,
    tax: 40.50,
    total: 450.50,
    status: 'Pending',
    date: 'Today, 09:15 AM',
    notes: 'Awaiting credit authorization approval',
    paymentTerms: 'Net 30 Terms',
  },
  {
    id: '#ORD-0919',
    customer: 'Dr. Smith Practice',
    customerId: 'cust-4',
    customerContact: 'Dr. Gregory Smith',
    items: [
      {
        id: 'item-4',
        medicineId: 'med-ato-020',
        medicineName: 'Atorvastatin 20mg',
        sku: 'ATO-20-TAB',
        quantity: 40,
        unitPrice: 18.90,
        total: 756.00,
      }
    ],
    subtotal: 756.00,
    discount: 0,
    tax: 134.00,
    total: 890.00,
    status: 'Success',
    date: 'Yesterday',
    notes: 'Delivered via courier and signed by receptionist',
    paymentTerms: 'Net 15 Terms',
  },
  {
    id: '#ORD-0918',
    customer: 'Central Pharmacy',
    customerId: 'cust-5',
    customerContact: 'Pharm. Angela Ray',
    items: [
      {
        id: 'item-5',
        medicineId: 'med-amx-500',
        medicineName: 'Amoxicillin 500mg',
        sku: 'MED-AMX-500-001',
        quantity: 120,
        unitPrice: 12.50,
        total: 1500.00,
      },
      {
        id: 'item-6',
        medicineId: 'med-ome-020',
        medicineName: 'Omeprazole 20mg',
        sku: 'OME-20-CAP',
        quantity: 50,
        unitPrice: 11.20,
        total: 560.00,
      }
    ],
    subtotal: 2060.00,
    discount: 20.00,
    tax: 60.00,
    total: 2100.00,
    status: 'Success',
    date: 'Yesterday',
    notes: 'Regular bi-weekly restock order',
    paymentTerms: 'Net 30 Terms',
  }
];

export const initialPredictiveAlerts: AIPredictiveAlert[] = [
  {
    id: 'ai-alert-1',
    medicineId: 'med-amx-500',
    medicineName: 'Amoxicillin 500mg',
    sku: 'AMX-500-CAP',
    riskLevelText: 'High Risk (7 Days)',
    riskSeverity: 'high',
    currentStock: 1240,
    predictedVelocity: 185,
    leadTimeDays: 5,
    predictedDays: 7,
    confidence: 92,
    insightDescription: 'Predicted high demand in next 10 days due to upcoming seasonal flu trends matching historical data patterns for this region.',
    recommendedAction: 'Create Reorder PO of 2,500 boxes from PharmaCorp Inc.'
  },
  {
    id: 'ai-alert-2',
    medicineId: 'med-ibu-400',
    medicineName: 'Ibuprofen 400mg Tabs',
    sku: 'IBU-400-TAB',
    riskLevelText: 'Critical Risk (2 Days)',
    riskSeverity: 'critical',
    currentStock: 450,
    predictedVelocity: 210,
    leadTimeDays: 7,
    predictedDays: 2,
    confidence: 95,
    insightDescription: 'Critical stock deficit looming. Run rate exceeds regional supply replenishment window by 5 days.',
    recommendedAction: 'Immediate Expedited Reorder PO of 5,000 units from Generic Health Co.'
  }
];
